#!/usr/bin/env python3

"""Generate the embedded low-poly Suzanne control mesh with Blender."""

from __future__ import annotations

import argparse
import hashlib
import math
from pathlib import Path
import struct
import sys

import bpy


EXPECTED_VERTEX_COUNT = 507
EXPECTED_FACE_COUNT = 500
EXPECTED_TRIANGLE_COUNT = 968


def parse_arguments() -> argparse.Namespace:
    script_arguments = sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/graphics/suzanne_control_mesh.hpp"),
        help="Generated C++ header path",
    )
    return parser.parse_args(script_arguments)


def to_application_axes(vector: tuple[float, float, float]) -> tuple[float, float, float]:
    x, y, z = vector
    return x, z, -y


def normalize(vector: tuple[float, float, float]) -> tuple[float, float, float]:
    length = math.sqrt(sum(component * component for component in vector))
    if not math.isfinite(length) or length <= 0.0:
        raise ValueError("Suzanne contains a non-finite or zero-length normal.")
    return tuple(component / length for component in vector)


def format_float(value: float) -> str:
    value = struct.unpack("<f", struct.pack("<f", value))[0]
    if value == 0.0:
        return "0.0F"

    text = format(value, ".9g")
    if "." not in text and "e" not in text:
        text += ".0"
    return text + "F"


def control_cage_hash(mesh: bpy.types.Mesh) -> str:
    digest = hashlib.sha256()
    for vertex in mesh.vertices:
        digest.update(struct.pack("<3f", *vertex.co))
    for polygon in mesh.polygons:
        digest.update(struct.pack("<B", len(polygon.vertices)))
        digest.update(struct.pack(f"<{len(polygon.vertices)}H", *polygon.vertices))
    return digest.hexdigest().upper()


def write_header(output_path: Path, mesh: bpy.types.Mesh) -> None:
    if len(mesh.vertices) != EXPECTED_VERTEX_COUNT or len(mesh.polygons) != EXPECTED_FACE_COUNT:
        raise ValueError("Blender's factory Suzanne control cage has unexpected counts.")

    mesh.calc_loop_triangles()
    if len(mesh.loop_triangles) != EXPECTED_TRIANGLE_COUNT:
        raise ValueError("Blender's Suzanne triangulation has an unexpected triangle count.")

    positions = [to_application_axes(tuple(vertex.co)) for vertex in mesh.vertices]
    minimum = tuple(min(position[axis] for position in positions) for axis in range(3))
    maximum = tuple(max(position[axis] for position in positions) for axis in range(3))
    center = tuple((minimum[axis] + maximum[axis]) * 0.5 for axis in range(3))
    centered = [
        tuple(position[axis] - center[axis] for axis in range(3)) for position in positions
    ]
    maximum_radius = max(
        math.sqrt(sum(component * component for component in position))
        for position in centered
    )
    if not math.isfinite(maximum_radius) or maximum_radius <= 0.0:
        raise ValueError("Suzanne positions do not define a finite nonzero surface.")

    normalized_positions = [
        tuple(component / maximum_radius for component in position) for position in centered
    ]
    normals = [
        normalize(to_application_axes(tuple(vertex.normal))) for vertex in mesh.vertices
    ]
    indices = [index for triangle in mesh.loop_triangles for index in triangle.vertices]

    vertex_lines = [
        "    MeshVertex{.position = {"
        + ", ".join(format_float(component) for component in position)
        + "}, .normal = {"
        + ", ".join(format_float(component) for component in normal)
        + "}}"
        for position, normal in zip(normalized_positions, normals, strict=True)
    ]
    index_lines = [
        "    " + ", ".join(f"{index}U" for index in indices[offset : offset + 12])
        for offset in range(0, len(indices), 12)
    ]

    output = f'''#pragma once

#include "graphics/mesh_data.hpp"

#include <array>
#include <cstdint>
#include <string_view>

namespace qws::suzanne_control_mesh {{

// Generated by tools/generate_suzanne_control_mesh.py. Do not edit manually.
inline constexpr std::string_view blender_version = "{bpy.app.version_string}";
inline constexpr std::string_view control_cage_sha256 =
    "{control_cage_hash(mesh)}";
// clang-format off
inline constexpr std::array<MeshVertex, {len(vertex_lines)}> vertices{{
{',\n'.join(vertex_lines)},
}};
inline constexpr std::array<std::uint32_t, {len(indices)}> indices{{
{',\n'.join(index_lines)},
}};
// clang-format on

}} // namespace qws::suzanne_control_mesh
'''
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8", newline="\n")


def main() -> None:
    arguments = parse_arguments()
    bpy.ops.mesh.primitive_monkey_add()
    mesh = bpy.context.object.data
    mesh.validate()
    mesh.update(calc_edges=True, calc_edges_loose=True)
    write_header(arguments.output, mesh)
    print(
        f"Embedded Suzanne control cage: {len(mesh.vertices)} vertices, "
        f"{len(mesh.loop_triangles)} triangles."
    )


if __name__ == "__main__":
    main()
